name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build & Test
    env:
      BUILD_CONFIG: Release

    runs-on: ubuntu-latest
    continue-on-error: false

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        source-url: https://api.nuget.org/v3/index.json
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c $BUILD_CONFIG --no-restore -p:TreatWarningsAsErrors=true
    - name: Test
      run: dotnet test -c $BUILD_CONFIG --no-build --verbosity normal
